name: Build all platforms

on: [ push, pull_request ]

jobs:
  crossbuild:
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build containers
      run: make all-container
